# Generated by Django 4.1.6 on 2023-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230211_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='test description', max_length=100),
            preserve_default=False,
        ),
    ]
