# Generated by Django 4.1.6 on 2023-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imageUrl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/2/2c/Venom_soundtrack_cover.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
