# Generated by Django 4.1.6 on 2023-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imageUrl',
            field=models.CharField(max_length=150),
        ),
    ]
